#########################################################################
# Title:         Cloudbox: Freespace Role                               #
# Author(s):     Stokkes                                                #
# URL:           https://github.com/stokkes/cloudbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---  
- name: Create script directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/scripts

- name: Create freespace-check script
  template:
    src: freespace-check.sh.js2
    dest: "/opt/scripts/freespace-check.sh"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0755

- name: Create cron job for freespace-check
  cron:
    name: "Freespace check"
    user: "{{user}}"
    minute: "{{ freespace.cron_minute | default('5') }}"
    job: "/bin/bash -c /opt/scripts/freespace-check.sh"