#########################################################################
# Title:         Cloudbox: Glances Role                               #
# Author(s):     Stokkes                                                #
# URL:           https://github.com/stokkes/cloudbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: glances
    state: absent

- name: Create Glances container
  docker_container:
    name: glances
    image: "nicolargo/glances"
    pull: yes
    restart_policy: unless-stopped
    network_mode: host
    pid_mode: host
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    env:
      HOST_OS: "Ubuntu"
      GLANCES_OPT: "-w"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    state: started
